name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "论secrets会对明文猜中的密码进行日志屏蔽"
      # secrets.SIGNING_KEY 的值12345
      # secrets.SIGNING_KEY_ID 的值54321
        run: |
          echo "password is 12345"
          echo "password is 54321"  
          echo "password is ${{ secrets.SIGNING_KEY }}"
      - name: "论没有secrets不会对明文猜中的密码进行日志屏蔽？"
      # secrets.SIGNING_KEY 的值12345
      # secrets.SIGNING_KEY_ID 的值54321
        run: |
          echo "password is 12345"
          echo "password is 54321"  
