name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env:
          SK: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "password is 12345"
          echo "password is ${SK}"
          echo "password is ${{ secrets.SIGNING_KEY }}"
